In [12]:
# Import libraries
import pandas as pd
import os

# Define file paths and load data
data_path = "../unprocessed-data"
season_file = "nba_player_stats_2023-24.csv" # 23-24 season for intial testing
file_path = os.path.join(data_path, season_file)
season_data = pd.read_csv(file_path)

pd.set_option('display.max_columns', None)
season_data.head() # Test successful load

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Season
0,Joel Embiid,29.0,PHI,C,39.0,39.0,33.6,11.5,21.8,0.529,1.4,3.6,0.388,10.2,18.3,0.556,0.561,10.2,11.6,0.883,2.4,8.6,11.0,5.6,1.2,1.7,3.8,2.9,34.7,AS,2023-24
1,Luka Dončić,24.0,DAL,PG,70.0,70.0,37.5,11.5,23.6,0.487,4.1,10.6,0.382,7.4,13.0,0.573,0.573,6.8,8.7,0.786,0.8,8.4,9.2,9.8,1.4,0.5,4.0,2.1,33.9,"MVP-3,CPOY-6,AS,NBA1",2023-24
2,Giannis Antetokounmpo,29.0,MIL,PF,73.0,73.0,35.2,11.5,18.8,0.611,0.5,1.7,0.274,11.0,17.1,0.645,0.624,7.0,10.7,0.657,2.7,8.8,11.5,6.5,1.2,1.1,3.4,2.9,30.4,"MVP-4,DPOY-9,CPOY-12,AS,NBA1",2023-24
3,Shai Gilgeous-Alexander,25.0,OKC,PG,75.0,75.0,34.0,10.6,19.8,0.535,1.3,3.6,0.353,9.3,16.2,0.576,0.567,7.6,8.7,0.874,0.9,4.7,5.5,6.2,2.0,0.9,2.2,2.5,30.1,"MVP-2,DPOY-7,CPOY-3,AS,NBA1",2023-24
4,Jalen Brunson,27.0,NYK,PG,77.0,77.0,35.4,10.3,21.4,0.479,2.7,6.8,0.401,7.5,14.6,0.516,0.543,5.5,6.5,0.847,0.6,3.1,3.6,6.7,0.9,0.2,2.4,1.9,28.7,"MVP-5,CPOY-5,AS,NBA2",2023-24

In [13]:
# Combine season data into a single data structure
season_files = [file for file in os.listdir(data_path) if file.endswith('.csv')]
all_season_data = []

# Iterate through datasets and concatenate
for season_data_file in season_files:
    file_path = os.path.join(data_path, season_data_file)
    season_df = pd.read_csv(file_path)  # Renamed variable to avoid conflict
    all_season_data.append(season_df)

# Concatenate all the dataframes into one large dataframe
combined_data = pd.concat(all_season_data, ignore_index=True)

# Display the first/last few rows of the combined dataset
combined_data

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Season
0,Adrian Dantley,25.0,UTA,SF,80.0,NaN,42.7,11.4,20.3,0.559,0.0,0.1,0.286,11.3,20.3,0.560,0.559,7.9,9.8,0.806,2.4,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,"MVP-12,AS,NBA2",1980-81
1,Moses Malone,25.0,HOU,C,80.0,NaN,40.6,10.1,19.3,0.522,0.0,0.0,0.333,10.1,19.3,0.522,0.522,7.6,10.1,0.757,5.9,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,"MVP-4,AS,NBA2",1980-81
2,George Gervin,28.0,SAS,SG,82.0,82.0,33.7,10.4,21.1,0.492,0.1,0.4,0.257,10.3,20.7,0.496,0.494,6.2,7.6,0.826,1.5,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,"MVP-5,AS,NBA1",1980-81
3,Kareem Abdul-Jabbar,33.0,LAL,C,80.0,NaN,37.2,10.5,18.2,0.574,0.0,0.0,0.000,10.5,18.2,0.574,0.574,5.3,6.9,0.766,2.5,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,"MVP-3,AS,NBA1",1980-81
4,David Thompson,26.0,DEN,SG,77.0,NaN,34.0,9.5,18.8,0.506,0.1,0.5,0.256,9.4,18.3,0.513,0.509,6.4,8.0,0.795,1.4,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,NaN,1980-81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24060,Justin Minaya,25.0,POR,SF,1.0,0.0,6.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,2024-25
24061,Riley Minix,24.0,SAS,SF,1.0,0.0,7.0,0.0,1.0,0.000,0.0,1.0,0.000,0.0,0.0,NaN,0.000,0.0,0.0,NaN,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024-25
24062,Jalen Pickett,25.0,DEN,SG,2.0,0.0,2.0,0.0,0.5,0.000,0.0,0.5,0.000,0.0,0.0,NaN,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024-25
24063,Cole Swider,25.0,DET,SF,2.0,0.0,6.5,0.0,2.5,0.000,0.0,2.5,0.000,0.0,0.0,NaN,0.000,0.0,0.0,NaN,0.0,1.0,1.0,0.5,0.0,0.0,0.0,0.5,0.0,NaN,2024-25
24064,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.464,NaN,NaN,0.359,NaN,NaN,0.541,0.540,NaN,NaN,0.777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-25

In [14]:
# Show empty values in combined data
combined_data.isnull().sum()

Player        0
Age          45
Team         45
Pos          45
G            45
GS          345
MP           45
FG           45
FGA          45
FG%         130
3P           45
3PA          45
3P%        3793
2P           45
2PA          45
2P%         226
eFG%        130
FT           45
FTA          45
FT%        1154
ORB          45
DRB          45
TRB          45
AST          45
STL          45
BLK          45
TOV          45
PF           45
PTS          45
Awards    21821
Season        0
dtype: int64

In [15]:
# Calculate percentages from the raw values
combined_data['FG%'] = (combined_data['FG'] / combined_data['FGA']) * 100
combined_data['3P%'] = (combined_data['3P'] / combined_data['3PA']) * 100
combined_data['2P%'] = (combined_data['2P'] / combined_data['2PA']) * 100
combined_data['FT%'] = (combined_data['FT'] / combined_data['FTA']) * 100

# Calculate eFG% (Effective Field Goal Percentage)
combined_data['eFG%'] = ((combined_data['FG'] + 0.5 * combined_data['3P']) / combined_data['FGA']) * 100

# Handle division by zero (replace NaN values with 0 or another value)
combined_data['FG%'].fillna(0, inplace=True)
combined_data['3P%'].fillna(0, inplace=True)
combined_data['2P%'].fillna(0, inplace=True)
combined_data['FT%'].fillna(0, inplace=True)
combined_data['eFG%'].fillna(0, inplace=True)

# Show updated empty values in combined data
combined_data.isnull().sum()

Player        0
Age          45
Team         45
Pos          45
G            45
GS          345
MP           45
FG           45
FGA          45
FG%           0
3P           45
3PA          45
3P%           0
2P           45
2PA          45
2P%           0
eFG%          0
FT           45
FTA          45
FT%           0
ORB          45
DRB          45
TRB          45
AST          45
STL          45
BLK          45
TOV          45
PF           45
PTS          45
Awards    21821
Season        0
dtype: int64

In [16]:
# Drop lines representing 'League Average'
combined_data = combined_data[combined_data['Player'] != 'League Average']

# Show updated empty values in combined data
combined_data.isnull().sum()

Player        0
Age           0
Team          0
Pos           0
G             0
GS          300
MP            0
FG            0
FGA           0
FG%           0
3P            0
3PA           0
3P%           0
2P            0
2PA           0
2P%           0
eFG%          0
FT            0
FTA           0
FT%           0
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Awards    21776
Season        0
dtype: int64

In [17]:
# Most NaN for GS come from players in the 1980-81 season, add 0 values since data is from long ago
combined_data['GS'] = combined_data['GS'].fillna(0)

# Add 'No Award' value for 'Awards' column where Awards is NaN
combined_data.loc[combined_data['Awards'].isna(), 'Awards'] = "No Awards"

# Show updated empty values in combined data
combined_data.isnull().sum()

C:\Users\James Crespo\AppData\Local\Temp\ipykernel_37928\1117744735.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_data['GS'] = combined_data['GS'].fillna(0)

Player    0
Age       0
Team      0
Pos       0
G         0
GS        0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
2P        0
2PA       0
2P%       0
eFG%      0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
Awards    0
Season    0
dtype: int64

In [18]:
# Add TS% column to the combined dataset
combined_data['TS%'] = combined_data.apply(
    lambda row: (row['PTS'] / (2 * (row['FGA'] + 0.44 * row['FTA'])) * 100)
    if (row['FGA'] + 0.44 * row['FTA']) > 0 else 0, axis=1
)

# Display the updated DataFrame
combined_data.head()

C:\Users\James Crespo\AppData\Local\Temp\ipykernel_37928\1277164970.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_data['TS%'] = combined_data.apply(

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Season,TS%
0,Adrian Dantley,25.0,UTA,SF,80.0,0.0,42.7,11.4,20.3,56.157635,0.0,0.1,0.0,11.3,20.3,55.665025,56.157635,7.9,9.8,80.612245,2.4,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,"MVP-12,AS,NBA2",1980-81,62.367951
1,Moses Malone,25.0,HOU,C,80.0,0.0,40.6,10.1,19.3,52.331606,0.0,0.0,0.0,10.1,19.3,52.331606,52.331606,7.6,10.1,75.247525,5.9,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,"MVP-4,AS,NBA2",1980-81,58.541105
2,George Gervin,28.0,SAS,SG,82.0,82.0,33.7,10.4,21.1,49.289100,0.1,0.4,25.0,10.3,20.7,49.758454,49.526066,6.2,7.6,81.578947,1.5,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,"MVP-5,AS,NBA1",1980-81,55.432826
3,Kareem Abdul-Jabbar,33.0,LAL,C,80.0,0.0,37.2,10.5,18.2,57.692308,0.0,0.0,0.0,10.5,18.2,57.692308,57.692308,5.3,6.9,76.811594,2.5,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,"MVP-3,AS,NBA1",1980-81,61.687700
4,David Thompson,26.0,DEN,SG,77.0,0.0,34.0,9.5,18.8,50.531915,0.1,0.5,20.0,9.4,18.3,51.366120,50.797872,6.4,8.0,80.000000,1.4,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,No Awards,1980-81,57.123656

In [19]:
# Add EFF column to the combined dataset
combined_data['EFF'] = combined_data.apply(
    lambda row: (
        (row['PTS'] + row['TRB'] + row['AST'] + row['STL'] + row['BLK'] -
         (row['FGA'] - row['FG']) - (row['FTA'] - row['FT']) - row['TOV']) / row['G'] * 100
    ) if row['G'] > 0 else 0, axis=1
)

# Display the updated DataFrame
combined_data.head()

C:\Users\James Crespo\AppData\Local\Temp\ipykernel_37928\4052313130.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_data['EFF'] = combined_data.apply(

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Season,TS%,EFF
0,Adrian Dantley,25.0,UTA,SF,80.0,0.0,42.7,11.4,20.3,56.157635,0.0,0.1,0.0,11.3,20.3,55.665025,56.157635,7.9,9.8,80.612245,2.4,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,"MVP-12,AS,NBA2",1980-81,62.367951,35.500000
1,Moses Malone,25.0,HOU,C,80.0,0.0,40.6,10.1,19.3,52.331606,0.0,0.0,0.0,10.1,19.3,52.331606,52.331606,7.6,10.1,75.247525,5.9,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,"MVP-4,AS,NBA2",1980-81,58.541105,39.625000
2,George Gervin,28.0,SAS,SG,82.0,82.0,33.7,10.4,21.1,49.289100,0.1,0.4,25.0,10.3,20.7,49.758454,49.526066,6.2,7.6,81.578947,1.5,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,"MVP-5,AS,NBA1",1980-81,55.432826,26.829268
3,Kareem Abdul-Jabbar,33.0,LAL,C,80.0,0.0,37.2,10.5,18.2,57.692308,0.0,0.0,0.0,10.5,18.2,57.692308,57.692308,5.3,6.9,76.811594,2.5,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,"MVP-3,AS,NBA1",1980-81,61.687700,38.875000
4,David Thompson,26.0,DEN,SG,77.0,0.0,34.0,9.5,18.8,50.531915,0.1,0.5,20.0,9.4,18.3,51.366120,50.797872,6.4,8.0,80.000000,1.4,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,No Awards,1980-81,57.123656,25.454545

In [20]:
print(combined_data.columns, "\n")
# Reorder Features
columns = ['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
           '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
           'TS%', 'EFF', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 
           'Awards', 'Season']

# Apply the new column order
combined_data = combined_data[columns]

# Print the columns and dataFrame
print(combined_data.columns, "\n")

combined_data.head(5)

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Awards',
       'Season', 'TS%', 'EFF'],
      dtype='object')

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'TS%', 'EFF', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'Awards', 'Season'],
      dtype='object')

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,TS%,EFF,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Season
0,Adrian Dantley,25.0,UTA,SF,80.0,0.0,42.7,11.4,20.3,56.157635,0.0,0.1,0.0,11.3,20.3,55.665025,56.157635,7.9,9.8,80.612245,62.367951,35.500000,2.4,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,"MVP-12,AS,NBA2",1980-81
1,Moses Malone,25.0,HOU,C,80.0,0.0,40.6,10.1,19.3,52.331606,0.0,0.0,0.0,10.1,19.3,52.331606,52.331606,7.6,10.1,75.247525,58.541105,39.625000,5.9,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,"MVP-4,AS,NBA2",1980-81
2,George Gervin,28.0,SAS,SG,82.0,82.0,33.7,10.4,21.1,49.289100,0.1,0.4,25.0,10.3,20.7,49.758454,49.526066,6.2,7.6,81.578947,55.432826,26.829268,1.5,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,"MVP-5,AS,NBA1",1980-81
3,Kareem Abdul-Jabbar,33.0,LAL,C,80.0,0.0,37.2,10.5,18.2,57.692308,0.0,0.0,0.0,10.5,18.2,57.692308,57.692308,5.3,6.9,76.811594,61.687700,38.875000,2.5,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,"MVP-3,AS,NBA1",1980-81
4,David Thompson,26.0,DEN,SG,77.0,0.0,34.0,9.5,18.8,50.531915,0.1,0.5,20.0,9.4,18.3,51.366120,50.797872,6.4,8.0,80.000000,57.123656,25.454545,1.4,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,No Awards,1980-81

In [28]:
# Adding Team Wins, Losses, and Win/Loss % columns to each player
import pandas as pd
team_win_data_df = pd.read_csv('../processed-data/prepared_team_win_data.csv')
# Check
team_win_data_df

,Season,ATL,BOS,BRK,CHI,CHO,CLE,DAL,DEN,DET,GSW,HOU,IND,LAC,LAL,MEM,MIA,MIL,MIN,NOP,NYK,OKC,ORL,PHI,PHO,POR,SAC,SAS,TOR,UTA,WAS
0,2024,14,21,10,12,7.0,23,17,14,11,14,17,12,15,14,18.0,13.0,14,14.0,5.0,16,20,17.0,8,14,8,13,13,7.0,5,3
1,2023,36,64,32,39,21.0,48,50,57,14,46,41,47,51,47,27.0,46.0,49,56.0,49.0,50,57,47.0,47,49,21,46,22,25.0,31,15
2,2022,41,57,45,40,27.0,51,38,53,17,44,22,35,44,43,51.0,44.0,58,42.0,42.0,47,40,34.0,54,45,33,48,22,41.0,37,35
3,2021,43,51,44,46,43.0,44,52,48,23,53,20,25,42,33,56.0,53.0,51,46.0,36.0,37,24,22.0,51,64,27,30,34,48.0,49,35
4,2020,41,36,48,31,33.0,22,42,47,20,39,17,34,47,42,38.0,40.0,46,23.0,31.0,41,22,21.0,49,51,42,31,33,27.0,52,34
5,2019,20,48,35,22,23.0,19,43,46,20,15,44,45,49,52,34.0,44.0,56,19.0,30.0,21,44,33.0,43,34,35,31,32,53.0,44,25
6,2018,29,49,42,22,39.0,19,33,54,41,57,53,48,48,37,33.0,39.0,60,36.0,33.0,17,49,42.0,51,19,53,39,48,58.0,50,32
7,2017,24,55,28,27,36.0,50,24,46,39,58,65,48,42,35,22.0,44.0,44,47.0,48.0,29,48,25.0,52,21,49,27,47,59.0,48,43
8,2016,43,53,20,41,36.0,51,33,40,37,67,55,42,51,26,43.0,41.0,42,31.0,34.0,31,47,29.0,28,24,41,32,61,51.0,51,49
9,2015,48,48,21,42,48.0,57,42,33,44,73,41,45,53,17,42.0,48.0,33,29.0,30.0,32,55,35.0,10,23,44,33,67,56.0,40,41
10,2014,60,40,38,50,33.0,53,50,30,32,67,56,38,56,21,55.0,37.0,41,16.0,45.0,17,45,25.0,18,39,51,29,55,49.0,38,46
11,2013,38,25,44,48,43.0,33,49,36,29,51,54,56,57,27,50.0,54.0,15,40.0,34.0,37,59,23.0,19,48,54,28,62,48.0,25,44
12,2012,44,41,49,45,21.0,24,41,57,29,47,45,49,56,45,56.0,66.0,38,31.0,27.0,54,60,20.0,34,25,33,28,58,34.0,43,29
13,2011,40,39,22,50,7.0,21,36,38,25,23,34,42,40,41,41.0,46.0,31,26.0,21.0,36,47,37.0,35,33,28,22,50,23.0,36,20
14,2010,44,56,24,62,34.0,19,57,50,30,36,43,37,32,57,46.0,58.0,35,17.0,46.0,42,55,52.0,41,40,48,24,61,22.0,39,23
15,2009,53,50,12,41,44.0,61,55,53,27,26,42,32,29,57,40.0,47.0,46,15.0,37.0,29,50,59.0,27,54,50,25,50,40.0,53,26
16,2008,47,62,34,41,35.0,66,50,54,39,29,53,36,19,65,24.0,43.0,34,24.0,49.0,32,23,59.0,41,46,54,17,54,33.0,48,19
17,2007,37,66,34,33,32.0,45,51,50,59,48,55,36,23,57,22.0,15.0,26,22.0,56.0,23,20,52.0,40,55,41,38,56,41.0,54,43
18,2006,30,24,41,49,33.0,50,67,45,53,42,52,35,40,42,22.0,44.0,28,32.0,39.0,33,31,40.0,35,61,32,33,58,47.0,51,41
19,2005,26,33,49,41,26.0,50,60,44,64,34,34,41,47,45,49.0,52.0,40,33.0,38.0,23,35,36.0,38,54,21,44,63,27.0,41,42
20,2004,13,45,42,47,18.0,42,58,49,54,34,51,44,37,34,45.0,59.0,30,44.0,18.0,33,52,36.0,43,62,27,50,59,33.0,26,45
21,2003,28,36,47,23,NaN,35,52,43,54,37,45,61,28,56,50.0,42.0,41,58.0,41.0,39,37,21.0,33,29,41,55,57,33.0,42,25
22,2002,35,44,49,30,NaN,17,60,17,50,38,43,48,27,50,28.0,25.0,42,51.0,47.0,37,40,42.0,48,44,50,59,60,24.0,47,37
23,2001,33,49,52,21,44.0,29,57,27,50,21,28,42,39,58,23.0,36.0,41,50.0,NaN,30,45,44.0,43,36,49,61,58,42.0,44,37
24,2000,25,36,26,15,46.0,30,53,40,32,17,45,41,31,56,23.0,50.0,52,47.0,NaN,48,44,43.0,56,51,50,55,58,47.0,53,19
25,1999,28,35,31,17,49.0,32,40,35,42,19,34,56,15,67,22.0,52.0,42,50.0,NaN,50,45,41.0,49,53,59,44,53,45.0,55,29
26,1998,31,19,16,13,26.0,22,19,14,29,21,31,33,9,31,8.0,33.0,28,25.0,NaN,27,25,33.0,28,27,35,27,37,23.0,37,18
27,1997,50,36,43,62,51.0,47,20,11,37,19,41,58,17,61,19.0,55.0,36,45.0,NaN,43,61,41.0,31,56,46,27,56,16.0,62,42
28,1996,56,15,26,69,54.0,42,24,21,54,30,57,39,36,56,14.0,61.0,33,40.0,NaN,57,57,45.0,22,40,49,34,20,30.0,64,44
29,1995,46,33,30,72,41.0,47,26,35,46,36,48,52,29,53,15.0,42.0,25,26.0,NaN,47,64,60.0,18,41,44,39,59,21.0,55,39
30,1994,42,35,30,47,50.0,43,36,41,28,26,47,52,17,48,NaN,32.0,34,21.0,NaN,55,57,57.0,24,59,44,39,62,NaN,60,21
31,1993,57,32,45,55,41.0,47,13,42,20,50,58,47,27,33,NaN,42.0,20,20.0,NaN,57,63,50.0,25,56,47,28,55,NaN,53,24
32,1992,43,48,43,57,44.0,54,11,36,40,34,55,41,41,39,NaN,36.0,28,19.0,NaN,60,55,41.0,26,62,51,25,49,NaN,47,22
33,1991,38,51,40,67,31.0,57,22,24,48,55,42,40,45,43,NaN,38.0,31,15.0,NaN,51,47,21.0,35,53,57,29,47,NaN,55,25
34,1990,43,56,26,61,26.0,33,28,20,50,44,52,41,31,58,NaN,24.0,48,29.0,NaN,39,41,31.0,44,55,63,25,55,NaN,54,30
35,1989,41,52,17,55,19.0,42,47,43,59,37,41,42,30,63,NaN,18.0,44,22.0,NaN,45,41,18.0,53,54,59,23,56,NaN,55,31
36,1988,52,42,26,47,20.0,57,38,44,63,43,45,28,21,57,NaN,15.0,49,NaN,NaN,52,47,NaN,46,55,39,27,21,NaN,51,40
37,1987,50,57,19,50,NaN,42,53,54,54,20,46,38,17,62,NaN,NaN,42,NaN,NaN,38,44,NaN,36,28,53,24,31,NaN,47,38
38,1986,57,59,24,40,NaN,31,55,37,52,42,42,41,12,65,NaN,NaN,50,NaN,NaN,24,39,NaN,45,36,49,29,28,NaN,44,42
39,1985,50,67,39,30,NaN,29,44,47,46,30,51,26,32,62,NaN,NaN,57,NaN,NaN,23,31,NaN,54,32,40,37,35,NaN,42,39
40,1984,34,63,42,38,NaN,36,44,52,46,22,48,22,31,62,NaN,NaN,59,NaN,NaN,24,31,NaN,58,36,42,31,41,NaN,41,40
41,1983,40,62,45,27,NaN,28,43,38,49,37,29,26,30,54,NaN,NaN,50,NaN,NaN,47,42,NaN,52,41,48,38,37,NaN,45,35
42,1982,43,56,49,28,NaN,23,38,45,37,30,14,20,25,58,NaN,NaN,51,NaN,NaN,44,48,NaN,65,53,46,45,53,NaN,30,42
43,1981,42,63,44,34,NaN,15,28,46,39,45,46,35,17,57,NaN,NaN,55,NaN,NaN,33,52,NaN,58,46,42,30,48,NaN,25,43
44,1980,31,62,24,45,NaN,28,15,37,21,39,40,44,36,54,NaN,NaN,60,NaN,NaN,50,34,NaN,62,57,45,40,52,NaN,28,39

In [22]:
# Code block for writing/saving processed data

# Save combined dataframe to processed data directory
processed_data_path = "../processed-data/combined_data.csv"
combined_data.to_csv(processed_data_path, index=False)
print(f"Data saved to: {processed_data_path}") # Confirmation

Data saved to: ../processed-data/combined_data.csv